#!/bin/bash
for i in `cat /tmp/ping.ip`
do
        ping -c 2 $i > /dev/null

        if [ $? -eq 0 ]
        then
             echo "$i is UP"  | tee -a  /tmp/ok
        else
            echo "$i id down"  | tee -a  /tmp/notok
        fi
done
